from backend.database import SessionLocal, engine, Base
from backend.models import Fragrance
from backend.ml_model import ScentRecognitionModel
import random

FRAGRANCES_DATA = [
    {
        "name": "Sauvage",
        "brand": "Dior",
        "description": "A radically fresh composition, dictated by a name that has the scent of wide-open spaces. Sauvage is an act of creation inspired by wide-open spaces.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
        "top_notes": ["Bergamot", "Pepper"],
        "mid_notes": ["Lavender", "Pink Pepper", "Vetiver", "Geranium"],
        "base_notes": ["Ambroxan", "Cedar", "Labdanum"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2015,
        "longevity_hours": 8.0,
        "projection": "Strong",
        "price_min": 95.0,
        "price_max": 150.0,
        "avg_rating": 4.5,
        "review_count": 12500
    },
    {
        "name": "Bleu de Chanel",
        "brand": "Chanel",
        "description": "An ode to masculine freedom expressed in an aromatic-woody fragrance with a tonic, sensual trail.",
        "image_url": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400",
        "top_notes": ["Citrus", "Mint", "Pink Pepper"],
        "mid_notes": ["Grapefruit", "Ginger", "Nutmeg", "Jasmine"],
        "base_notes": ["Incense", "Vetiver", "Cedar", "Sandalwood"],
        "concentration": "Eau de Parfum",
        "gender": "Masculine",
        "year_released": 2010,
        "longevity_hours": 10.0,
        "projection": "Moderate",
        "price_min": 110.0,
        "price_max": 180.0,
        "avg_rating": 4.6,
        "review_count": 15000
    },
    {
        "name": "Acqua di Gio",
        "brand": "Giorgio Armani",
        "description": "Inspired by the beauty of Pantelleria, where earth, sea, and sky merge. A fresh aromatic fragrance.",
        "image_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
        "top_notes": ["Marine Notes", "Bergamot", "Neroli", "Green Tangerine"],
        "mid_notes": ["Jasmine", "Calone", "Peach", "Freesia", "Cyclamen", "Rose"],
        "base_notes": ["Cedar", "Musk", "Oakmoss", "Amber"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 1996,
        "longevity_hours": 6.0,
        "projection": "Moderate",
        "price_min": 80.0,
        "price_max": 135.0,
        "avg_rating": 4.4,
        "review_count": 20000
    },
    {
        "name": "La Vie Est Belle",
        "brand": "Lancome",
        "description": "A declaration of happiness, a smile to life. La vie est belle opens with a sparkling cocktail of pear and black currant.",
        "image_url": "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=400",
        "top_notes": ["Black Currant", "Pear"],
        "mid_notes": ["Iris", "Jasmine", "Orange Blossom"],
        "base_notes": ["Praline", "Vanilla", "Patchouli", "Tonka Bean"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2012,
        "longevity_hours": 8.0,
        "projection": "Strong",
        "price_min": 85.0,
        "price_max": 155.0,
        "avg_rating": 4.5,
        "review_count": 18000
    },
    {
        "name": "Coco Mademoiselle",
        "brand": "Chanel",
        "description": "A sexy, fresh oriental fragrance with a strong yet soft personality. An irresistible, irrepressible woman.",
        "image_url": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400",
        "top_notes": ["Orange", "Mandarin", "Bergamot"],
        "mid_notes": ["Rose", "Jasmine", "Ylang-Ylang", "Mimosa"],
        "base_notes": ["Patchouli", "Vetiver", "Vanilla", "White Musk"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2001,
        "longevity_hours": 9.0,
        "projection": "Moderate",
        "price_min": 105.0,
        "price_max": 175.0,
        "avg_rating": 4.7,
        "review_count": 22000
    },
    {
        "name": "Tom Ford Oud Wood",
        "brand": "Tom Ford",
        "description": "Oud Wood envelops you in rare oud, sandalwood, and vetiver. A warm, smoky blend of exotic woods.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Oud", "Rosewood", "Cardamom"],
        "mid_notes": ["Sandalwood", "Vetiver"],
        "base_notes": ["Tonka Bean", "Amber"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2007,
        "longevity_hours": 10.0,
        "projection": "Moderate",
        "price_min": 250.0,
        "price_max": 380.0,
        "avg_rating": 4.6,
        "review_count": 8500
    },
    {
        "name": "Black Opium",
        "brand": "Yves Saint Laurent",
        "description": "A highly addictive feminine fragrance. The first coffee-based scent, a modern interpretation of addiction.",
        "image_url": "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=400",
        "top_notes": ["Pink Pepper", "Orange Blossom", "Pear"],
        "mid_notes": ["Coffee", "Jasmine", "Bitter Almond"],
        "base_notes": ["Vanilla", "Patchouli", "Cedar", "Cashmere Wood"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2014,
        "longevity_hours": 8.0,
        "projection": "Strong",
        "price_min": 90.0,
        "price_max": 150.0,
        "avg_rating": 4.4,
        "review_count": 16000
    },
    {
        "name": "Aventus",
        "brand": "Creed",
        "description": "A sophisticated blend celebrating strength, power, and success. Top notes of blackcurrant and Italian bergamot.",
        "image_url": "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400",
        "top_notes": ["Pineapple", "Bergamot", "Black Currant", "Apple"],
        "mid_notes": ["Birch", "Patchouli", "Moroccan Jasmine", "Rose"],
        "base_notes": ["Musk", "Oakmoss", "Ambergris", "Vanilla"],
        "concentration": "Eau de Parfum",
        "gender": "Masculine",
        "year_released": 2010,
        "longevity_hours": 12.0,
        "projection": "Strong",
        "price_min": 350.0,
        "price_max": 445.0,
        "avg_rating": 4.8,
        "review_count": 9500
    },
    {
        "name": "Light Blue",
        "brand": "Dolce & Gabbana",
        "description": "Light Blue is the scent of a sensual Mediterranean summer. Fresh and fruity with Sicilian cedar and citrus.",
        "image_url": "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?w=400",
        "top_notes": ["Sicilian Lemon", "Apple", "Cedar", "Bellflower"],
        "mid_notes": ["Bamboo", "Jasmine", "White Rose"],
        "base_notes": ["Cedar", "Musk", "Amber"],
        "concentration": "Eau de Toilette",
        "gender": "Feminine",
        "year_released": 2001,
        "longevity_hours": 5.0,
        "projection": "Light",
        "price_min": 65.0,
        "price_max": 110.0,
        "avg_rating": 4.3,
        "review_count": 25000
    },
    {
        "name": "1 Million",
        "brand": "Paco Rabanne",
        "description": "A fresh, spicy, and woody fragrance housed in an iconic gold bar bottle. Daring and confident.",
        "image_url": "https://images.unsplash.com/photo-1542379653-b928db1f4848?w=400",
        "top_notes": ["Grapefruit", "Mint", "Blood Mandarin"],
        "mid_notes": ["Rose", "Cinnamon"],
        "base_notes": ["Leather", "White Wood", "Amber", "Patchouli"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2008,
        "longevity_hours": 7.0,
        "projection": "Strong",
        "price_min": 70.0,
        "price_max": 115.0,
        "avg_rating": 4.2,
        "review_count": 14000
    },
    {
        "name": "Miss Dior",
        "brand": "Dior",
        "description": "A floral tribute to the couturier's sister Catherine. Fresh and sparkling with Grasse rose.",
        "image_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
        "top_notes": ["Italian Mandarin", "Pink Pepper"],
        "mid_notes": ["Grasse Rose", "Damascus Rose", "Rosewood"],
        "base_notes": ["Musk", "Patchouli"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2012,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 95.0,
        "price_max": 160.0,
        "avg_rating": 4.5,
        "review_count": 11000
    },
    {
        "name": "Le Male",
        "brand": "Jean Paul Gaultier",
        "description": "A fresh oriental fragrance that has become an icon. Lavender and mint create a sensual virility.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
        "top_notes": ["Mint", "Lavender", "Bergamot", "Cardamom", "Artemisia"],
        "mid_notes": ["Orange Blossom", "Cumin", "Cinnamon"],
        "base_notes": ["Vanilla", "Tonka Bean", "Sandalwood", "Cedar", "Amber"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 1995,
        "longevity_hours": 6.0,
        "projection": "Moderate",
        "price_min": 65.0,
        "price_max": 100.0,
        "avg_rating": 4.4,
        "review_count": 17000
    },
    {
        "name": "Good Girl",
        "brand": "Carolina Herrera",
        "description": "A modern duality of light and dark. Jasmine and cocoa in an iconic stiletto bottle.",
        "image_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
        "top_notes": ["Almond", "Coffee", "Bergamot", "Lemon"],
        "mid_notes": ["Tuberose", "Jasmine Sambac", "Orange Blossom", "Rose"],
        "base_notes": ["Tonka Bean", "Cocoa", "Sandalwood", "Vanilla", "Cinnamon"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2016,
        "longevity_hours": 9.0,
        "projection": "Strong",
        "price_min": 90.0,
        "price_max": 145.0,
        "avg_rating": 4.3,
        "review_count": 13000
    },
    {
        "name": "Versace Eros",
        "brand": "Versace",
        "description": "For a strong, passionate man. The name of the God of love is a perfect tribute to masculinity.",
        "image_url": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400",
        "top_notes": ["Mint", "Green Apple", "Lemon"],
        "mid_notes": ["Tonka Bean", "Ambroxan", "Geranium"],
        "base_notes": ["Vanilla", "Vetiver", "Oakmoss", "Virginia Cedar"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2012,
        "longevity_hours": 8.0,
        "projection": "Strong",
        "price_min": 70.0,
        "price_max": 120.0,
        "avg_rating": 4.3,
        "review_count": 16500
    },
    {
        "name": "Flowerbomb",
        "brand": "Viktor & Rolf",
        "description": "A floral explosion. An addictive bouquet of cattleya, jasmine, freesia, and rose.",
        "image_url": "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=400",
        "top_notes": ["Tea", "Bergamot"],
        "mid_notes": ["Sambac Jasmine", "Cattleya Orchid", "Freesia", "Rose"],
        "base_notes": ["Patchouli", "Musk"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2005,
        "longevity_hours": 8.0,
        "projection": "Strong",
        "price_min": 100.0,
        "price_max": 175.0,
        "avg_rating": 4.5,
        "review_count": 14500
    },
    {
        "name": "Terre d'Hermes",
        "brand": "Hermes",
        "description": "An ode to the man who keeps his feet on the ground. Mineral and vegetal elements for a woody, earthy scent.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Orange", "Grapefruit", "Pepper"],
        "mid_notes": ["Pelargonium", "Geranium", "Patchouli"],
        "base_notes": ["Cedar", "Benzoin", "Vetiver"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2006,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 90.0,
        "price_max": 145.0,
        "avg_rating": 4.5,
        "review_count": 11500
    },
    {
        "name": "Mon Paris",
        "brand": "Yves Saint Laurent",
        "description": "A romantic and passionate fragrance. White peony and datura flower create a modern love story.",
        "image_url": "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=400",
        "top_notes": ["Strawberry", "Raspberry", "Pear"],
        "mid_notes": ["Peony", "Datura", "Jasmine"],
        "base_notes": ["White Musk", "Patchouli", "Ambroxan", "Cashmeran"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2016,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 85.0,
        "price_max": 140.0,
        "avg_rating": 4.2,
        "review_count": 9800
    },
    {
        "name": "Invictus",
        "brand": "Paco Rabanne",
        "description": "A champion's trophy fragrance. Fresh, marine, and woody with a burst of grapefruit.",
        "image_url": "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400",
        "top_notes": ["Grapefruit", "Marine Accord", "Mandarin"],
        "mid_notes": ["Jasmine", "Bay Leaf"],
        "base_notes": ["Oakmoss", "Patchouli", "Ambergris", "Guaiac Wood"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2013,
        "longevity_hours": 7.0,
        "projection": "Strong",
        "price_min": 70.0,
        "price_max": 115.0,
        "avg_rating": 4.2,
        "review_count": 13500
    },
    {
        "name": "Baccarat Rouge 540",
        "brand": "Maison Francis Kurkdjian",
        "description": "A luminous and sophisticated fragrance. Jasmine, saffron, and amberwood create an unmistakable aura.",
        "image_url": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400",
        "top_notes": ["Saffron", "Jasmine"],
        "mid_notes": ["Amberwood", "Maison Francis Kurkdjian Amber Accord"],
        "base_notes": ["Fir Resin", "Cedar"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2015,
        "longevity_hours": 12.0,
        "projection": "Strong",
        "price_min": 300.0,
        "price_max": 450.0,
        "avg_rating": 4.7,
        "review_count": 7500
    },
    {
        "name": "Ombre Leather",
        "brand": "Tom Ford",
        "description": "The American West as you've never seen it. Leather, moss, and patchouli under desert flower.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Cardamom", "Violet Leaf"],
        "mid_notes": ["Jasmine Sambac", "Leather"],
        "base_notes": ["Patchouli", "Vetiver", "Moss", "Amber"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2018,
        "longevity_hours": 10.0,
        "projection": "Moderate",
        "price_min": 150.0,
        "price_max": 250.0,
        "avg_rating": 4.5,
        "review_count": 6800
    },
    {
        "name": "Jo Malone English Pear & Freesia",
        "brand": "Jo Malone",
        "description": "The essence of autumn. Ripe pears wrapped in a bouquet of white freesias with amber and patchouli.",
        "image_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
        "top_notes": ["King William Pear", "Melon"],
        "mid_notes": ["Freesia", "Rose"],
        "base_notes": ["Musk", "Patchouli", "Rhubarb", "Amber"],
        "concentration": "Cologne",
        "gender": "Unisex",
        "year_released": 2010,
        "longevity_hours": 4.0,
        "projection": "Light",
        "price_min": 70.0,
        "price_max": 145.0,
        "avg_rating": 4.4,
        "review_count": 8200
    },
    {
        "name": "Chanel No. 5",
        "brand": "Chanel",
        "description": "The legendary fragrance. A timeless, elegant floral-aldehyde composition that has defined luxury since 1921.",
        "image_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
        "top_notes": ["Aldehydes", "Ylang-Ylang", "Neroli", "Bergamot", "Lemon"],
        "mid_notes": ["Jasmine", "Rose", "Lily of the Valley", "Iris"],
        "base_notes": ["Vetiver", "Musk", "Sandalwood", "Vanilla", "Amber"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 1921,
        "longevity_hours": 8.0,
        "projection": "Moderate",
        "price_min": 105.0,
        "price_max": 165.0,
        "avg_rating": 4.6,
        "review_count": 30000
    },
    {
        "name": "Dylan Blue",
        "brand": "Versace",
        "description": "A man of today. Citrus and aquatic notes with a woody, amber base for modern masculinity.",
        "image_url": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400",
        "top_notes": ["Calabrian Bergamot", "Grapefruit", "Fig Leaf", "Aquatic Notes"],
        "mid_notes": ["Violet Leaf", "Papyrus", "Patchouli", "Black Pepper", "Ambroxan"],
        "base_notes": ["Musk", "Tonka Bean", "Saffron", "Incense"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2016,
        "longevity_hours": 8.0,
        "projection": "Moderate",
        "price_min": 65.0,
        "price_max": 110.0,
        "avg_rating": 4.3,
        "review_count": 12000
    },
    {
        "name": "Gucci Bloom",
        "brand": "Gucci",
        "description": "A rich, white floral scent. Tuberose and jasmine bud create a garden of dreams.",
        "image_url": "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=400",
        "top_notes": ["Natural Tuberose", "Jasmine Bud"],
        "mid_notes": ["Tuberose", "Jasmine"],
        "base_notes": ["Rangoon Creeper"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2017,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 95.0,
        "price_max": 155.0,
        "avg_rating": 4.2,
        "review_count": 11000
    },
    {
        "name": "Y Eau de Parfum",
        "brand": "Yves Saint Laurent",
        "description": "Bold and audacious. A fusion of fresh and sensual notes for a new generation of men.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
        "top_notes": ["Apple", "Ginger", "Bergamot"],
        "mid_notes": ["Sage", "Juniper Berries", "Geranium"],
        "base_notes": ["Amberwood", "Tonka Bean", "Cedar", "Vetiver", "Olibanum"],
        "concentration": "Eau de Parfum",
        "gender": "Masculine",
        "year_released": 2018,
        "longevity_hours": 9.0,
        "projection": "Moderate",
        "price_min": 90.0,
        "price_max": 145.0,
        "avg_rating": 4.4,
        "review_count": 8500
    },
    {
        "name": "Marc Jacobs Daisy",
        "brand": "Marc Jacobs",
        "description": "A fresh, feminine floral bouquet. Violet leaf, wild strawberry, and white woods.",
        "image_url": "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?w=400",
        "top_notes": ["Strawberry", "Violet Leaf", "Ruby Red Grapefruit"],
        "mid_notes": ["Gardenia", "Violet Petals", "Jasmine"],
        "base_notes": ["Musk", "Vanilla", "White Woods"],
        "concentration": "Eau de Toilette",
        "gender": "Feminine",
        "year_released": 2007,
        "longevity_hours": 5.0,
        "projection": "Light",
        "price_min": 70.0,
        "price_max": 115.0,
        "avg_rating": 4.3,
        "review_count": 18500
    },
    {
        "name": "Boss Bottled",
        "brand": "Hugo Boss",
        "description": "The essence of success. A woody oriental fragrance for the ambitious man.",
        "image_url": "https://images.unsplash.com/photo-1542379653-b928db1f4848?w=400",
        "top_notes": ["Apple", "Lemon", "Bergamot", "Oakmoss", "Geranium"],
        "mid_notes": ["Cinnamon", "Mahogany", "Cloves", "Carnation"],
        "base_notes": ["Vanilla", "Sandalwood", "Cedar", "Vetiver", "Olive Tree"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 1998,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 60.0,
        "price_max": 100.0,
        "avg_rating": 4.2,
        "review_count": 19500
    },
    {
        "name": "Angel",
        "brand": "Mugler",
        "description": "The first gourmand fragrance. A revolutionary blend of patchouli and chocolate notes.",
        "image_url": "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=400",
        "top_notes": ["Helional", "Bergamot", "Hedione"],
        "mid_notes": ["Honey", "Apricot", "Blackberry", "Plum", "Jasmine", "Lily of the Valley", "Rose", "Dewberry"],
        "base_notes": ["Patchouli", "Vanilla", "Chocolate", "Caramel", "Sandalwood", "Musk", "Cedar", "Benzoin", "Coumarin"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 1992,
        "longevity_hours": 10.0,
        "projection": "Strong",
        "price_min": 75.0,
        "price_max": 140.0,
        "avg_rating": 4.3,
        "review_count": 14500
    },
    {
        "name": "Dior Homme",
        "brand": "Dior",
        "description": "Sophisticated and modern masculinity. Iris, lavender, and vetiver in perfect harmony.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Lavender", "Bergamot", "Sage"],
        "mid_notes": ["Iris", "Ambrette", "Cacao"],
        "base_notes": ["Vetiver", "Leather", "Virginia Cedar"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2005,
        "longevity_hours": 6.0,
        "projection": "Moderate",
        "price_min": 85.0,
        "price_max": 135.0,
        "avg_rating": 4.4,
        "review_count": 10500
    },
    {
        "name": "Alien",
        "brand": "Mugler",
        "description": "An elixir of absolute femininity. Solar notes and white amber for a radiant trail.",
        "image_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
        "top_notes": ["Jasmine Sambac"],
        "mid_notes": ["Cashmere Wood", "Cashmeran"],
        "base_notes": ["White Amber"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2005,
        "longevity_hours": 10.0,
        "projection": "Strong",
        "price_min": 80.0,
        "price_max": 145.0,
        "avg_rating": 4.4,
        "review_count": 12500
    },
    {
        "name": "Spicebomb",
        "brand": "Viktor & Rolf",
        "description": "An explosive cocktail of spices. Chili, saffron, and tobacco for a detonating trail.",
        "image_url": "https://images.unsplash.com/photo-1542379653-b928db1f4848?w=400",
        "top_notes": ["Bergamot", "Grapefruit", "Pink Pepper", "Elemi"],
        "mid_notes": ["Cinnamon", "Paprika", "Saffron", "Cumin"],
        "base_notes": ["Chili", "Tobacco", "Vetiver", "Leather"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2012,
        "longevity_hours": 8.0,
        "projection": "Moderate",
        "price_min": 85.0,
        "price_max": 130.0,
        "avg_rating": 4.3,
        "review_count": 9500
    },
    {
        "name": "Byredo Gypsy Water",
        "brand": "Byredo",
        "description": "A romanticized vision of the Romani lifestyle. Pine needles, incense, and orris butter.",
        "image_url": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400",
        "top_notes": ["Bergamot", "Lemon", "Pepper", "Juniper Berries"],
        "mid_notes": ["Incense", "Pine Needles", "Orris"],
        "base_notes": ["Amber", "Vanilla", "Sandalwood"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2008,
        "longevity_hours": 6.0,
        "projection": "Light",
        "price_min": 180.0,
        "price_max": 290.0,
        "avg_rating": 4.3,
        "review_count": 5500
    },
    {
        "name": "Armani Code",
        "brand": "Giorgio Armani",
        "description": "Seduction in a bottle. Lemon, olive flower, and tonka bean for irresistible allure.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
        "top_notes": ["Lemon", "Bergamot"],
        "mid_notes": ["Star Anise", "Olive Blossom", "Guaiac Wood"],
        "base_notes": ["Leather", "Tobacco", "Tonka Bean"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2004,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 75.0,
        "price_max": 125.0,
        "avg_rating": 4.2,
        "review_count": 16000
    },
    {
        "name": "Si",
        "brand": "Giorgio Armani",
        "description": "Modern and chic. Blackcurrant nectar, rose, and musky woody notes for confident femininity.",
        "image_url": "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=400",
        "top_notes": ["Blackcurrant Nectar", "Blackcurrant"],
        "mid_notes": ["May Rose", "Freesia"],
        "base_notes": ["Vanilla", "Ambroxan", "Patchouli", "Woody Notes", "Orcanox"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2013,
        "longevity_hours": 8.0,
        "projection": "Moderate",
        "price_min": 85.0,
        "price_max": 145.0,
        "avg_rating": 4.4,
        "review_count": 13500
    },
    {
        "name": "Club de Nuit Intense Man",
        "brand": "Armaf",
        "description": "A bold citrus-woody fragrance. Fresh bergamot and lemon with smoky birch and musk.",
        "image_url": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400",
        "top_notes": ["Lemon", "Pineapple", "Bergamot", "Black Currant", "Apple"],
        "mid_notes": ["Rose", "Birch", "Jasmine"],
        "base_notes": ["Musk", "Ambergris", "Patchouli", "Vanilla"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2015,
        "longevity_hours": 10.0,
        "projection": "Strong",
        "price_min": 25.0,
        "price_max": 45.0,
        "avg_rating": 4.3,
        "review_count": 22000
    },
    {
        "name": "Tobacco Vanille",
        "brand": "Tom Ford",
        "description": "Rich and spicy. Tobacco leaf, vanilla, cocoa, and dried fruits for opulent warmth.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Tobacco Leaf", "Spicy Notes"],
        "mid_notes": ["Vanilla", "Cacao", "Tonka Bean", "Tobacco Blossom"],
        "base_notes": ["Dried Fruits", "Woody Notes"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2007,
        "longevity_hours": 12.0,
        "projection": "Strong",
        "price_min": 260.0,
        "price_max": 390.0,
        "avg_rating": 4.6,
        "review_count": 7200
    },
    {
        "name": "Chance Eau Tendre",
        "brand": "Chanel",
        "description": "A tender and radiant floral fruity fragrance. Grapefruit, quince, and jasmine.",
        "image_url": "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
        "top_notes": ["Quince", "Grapefruit"],
        "mid_notes": ["Hyacinth", "Jasmine"],
        "base_notes": ["White Musk", "Iris", "Virginia Cedar", "Amber"],
        "concentration": "Eau de Toilette",
        "gender": "Feminine",
        "year_released": 2010,
        "longevity_hours": 6.0,
        "projection": "Moderate",
        "price_min": 95.0,
        "price_max": 155.0,
        "avg_rating": 4.4,
        "review_count": 11500
    },
    {
        "name": "Polo Blue",
        "brand": "Ralph Lauren",
        "description": "The spirit of freedom and adventure. Melon and cucumber with sage and basil.",
        "image_url": "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?w=400",
        "top_notes": ["Cucumber", "Melon"],
        "mid_notes": ["Basil", "Sage", "Geranium"],
        "base_notes": ["Musk", "Suede", "Wood"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2002,
        "longevity_hours": 6.0,
        "projection": "Moderate",
        "price_min": 70.0,
        "price_max": 115.0,
        "avg_rating": 4.2,
        "review_count": 13000
    },
    {
        "name": "D&G The One",
        "brand": "Dolce & Gabbana",
        "description": "Modern classic for men. Ginger, tobacco, and amber for magnetic sophistication.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
        "top_notes": ["Grapefruit", "Coriander", "Basil"],
        "mid_notes": ["Cardamom", "Ginger", "Orange Blossom", "Cedar"],
        "base_notes": ["Tobacco", "Amber", "Labdanum"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2008,
        "longevity_hours": 7.0,
        "projection": "Moderate",
        "price_min": 70.0,
        "price_max": 115.0,
        "avg_rating": 4.3,
        "review_count": 15000
    },
    {
        "name": "Narciso Rodriguez For Her",
        "brand": "Narciso Rodriguez",
        "description": "Sensual and timeless. A heart of musk with honey and amber undertones.",
        "image_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
        "top_notes": ["Orange Blossom", "Rose", "Osmanthus"],
        "mid_notes": ["Musc", "Amber"],
        "base_notes": ["Patchouli", "Sandalwood", "Vanilla", "Vetiver"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2003,
        "longevity_hours": 8.0,
        "projection": "Moderate",
        "price_min": 85.0,
        "price_max": 140.0,
        "avg_rating": 4.4,
        "review_count": 10500
    },
    {
        "name": "Libre",
        "brand": "Yves Saint Laurent",
        "description": "Free and fearless. Lavender essence and Moroccan orange blossom with bold vanilla.",
        "image_url": "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=400",
        "top_notes": ["Lavender Essence", "Mandarin Orange", "Black Currant Accord"],
        "mid_notes": ["Lavender", "Orange Blossom", "Jasmine"],
        "base_notes": ["Madagascar Vanilla", "Cedar", "Musk", "Ambergris"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2019,
        "longevity_hours": 9.0,
        "projection": "Strong",
        "price_min": 95.0,
        "price_max": 155.0,
        "avg_rating": 4.4,
        "review_count": 8500
    },
    {
        "name": "Replica Jazz Club",
        "brand": "Maison Margiela",
        "description": "Brooklyn jazz club. Tobacco leaf, rum absolute, and vetiver for a smoky evening.",
        "image_url": "https://images.unsplash.com/photo-1542379653-b928db1f4848?w=400",
        "top_notes": ["Pink Pepper", "Neroli", "Lemon"],
        "mid_notes": ["Rum Absolute", "Clary Sage", "Java Vetiver"],
        "base_notes": ["Tobacco Leaf", "Vanilla Bean", "Styrax Resin"],
        "concentration": "Eau de Toilette",
        "gender": "Unisex",
        "year_released": 2012,
        "longevity_hours": 6.0,
        "projection": "Moderate",
        "price_min": 130.0,
        "price_max": 175.0,
        "avg_rating": 4.3,
        "review_count": 6500
    },
    {
        "name": "Prada Luna Rossa Carbon",
        "brand": "Prada",
        "description": "High-tech masculinity. Lavender and metallic notes with ambroxan and patchouli.",
        "image_url": "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400",
        "top_notes": ["Bergamot", "Lavender"],
        "mid_notes": ["Metallic Notes"],
        "base_notes": ["Ambroxan", "Patchouli"],
        "concentration": "Eau de Toilette",
        "gender": "Masculine",
        "year_released": 2017,
        "longevity_hours": 9.0,
        "projection": "Strong",
        "price_min": 85.0,
        "price_max": 135.0,
        "avg_rating": 4.4,
        "review_count": 9800
    },
    {
        "name": "Delina",
        "brand": "Parfums de Marly",
        "description": "Royal and romantic. Turkish rose, lily of the valley, and cashmeran for elegant femininity.",
        "image_url": "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400",
        "top_notes": ["Litchi", "Rhubarb", "Bergamot", "Nutmeg"],
        "mid_notes": ["Turkish Rose", "Peony", "Vanilla"],
        "base_notes": ["Cashmeran", "White Musk", "Cedarwood", "Incense"],
        "concentration": "Eau de Parfum",
        "gender": "Feminine",
        "year_released": 2017,
        "longevity_hours": 10.0,
        "projection": "Strong",
        "price_min": 250.0,
        "price_max": 330.0,
        "avg_rating": 4.5,
        "review_count": 5800
    },
    {
        "name": "Molecule 01",
        "brand": "Escentric Molecules",
        "description": "Pure Iso E Super. A single molecule that reacts uniquely with each wearer's skin.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Iso E Super"],
        "mid_notes": ["Iso E Super"],
        "base_notes": ["Iso E Super"],
        "concentration": "Eau de Toilette",
        "gender": "Unisex",
        "year_released": 2006,
        "longevity_hours": 8.0,
        "projection": "Light",
        "price_min": 95.0,
        "price_max": 145.0,
        "avg_rating": 4.2,
        "review_count": 7500
    },
    {
        "name": "Oudh Accord & Gold",
        "brand": "Molton Brown",
        "description": "Luxurious and regal. Precious oud, saffron, and rose gold for opulent sophistication.",
        "image_url": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
        "top_notes": ["Bergamot", "Black Pepper"],
        "mid_notes": ["Saffron", "Rose", "Oud"],
        "base_notes": ["Sandalwood", "Vetiver", "Labdanum"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2017,
        "longevity_hours": 8.0,
        "projection": "Moderate",
        "price_min": 130.0,
        "price_max": 180.0,
        "avg_rating": 4.3,
        "review_count": 4200
    },
    {
        "name": "Mancera Cedrat Boise",
        "brand": "Mancera",
        "description": "Fresh and woody. Citrus zest, black currant, and oud wood for dynamic intensity.",
        "image_url": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400",
        "top_notes": ["Sicilian Lemon", "Black Currant", "Spicy Notes", "Bergamot"],
        "mid_notes": ["Patchouli Leaves", "Cedarwood"],
        "base_notes": ["White Musk", "Sandalwood", "Oakmoss", "Leather", "Vanilla"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2011,
        "longevity_hours": 12.0,
        "projection": "Strong",
        "price_min": 75.0,
        "price_max": 145.0,
        "avg_rating": 4.4,
        "review_count": 6800
    },
    {
        "name": "Initio Oud for Greatness",
        "brand": "Initio",
        "description": "Power and success. Rare oud, saffron, and lavender for magnetic presence.",
        "image_url": "https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=400",
        "top_notes": ["Nutmeg", "Lavender", "Saffron"],
        "mid_notes": ["Oud"],
        "base_notes": ["Musk"],
        "concentration": "Eau de Parfum",
        "gender": "Unisex",
        "year_released": 2018,
        "longevity_hours": 12.0,
        "projection": "Strong",
        "price_min": 290.0,
        "price_max": 380.0,
        "avg_rating": 4.5,
        "review_count": 4500
    }
]


def seed_fragrances():
    db = SessionLocal()
    ml_model = ScentRecognitionModel()
    
    try:
        existing_count = db.query(Fragrance).count()
        if existing_count > 0:
            print(f"Database already has {existing_count} fragrances. Skipping seed.")
            return
        
        for data in FRAGRANCES_DATA:
            notes_profile = {
                "top_notes": data.get("top_notes", []),
                "mid_notes": data.get("mid_notes", []),
                "base_notes": data.get("base_notes", [])
            }
            voc_vector = ml_model.generate_synthetic_vector(notes_profile)
            
            fragrance = Fragrance(
                name=data["name"],
                brand=data["brand"],
                description=data.get("description"),
                image_url=data.get("image_url"),
                voc_signature_vector=voc_vector,
                top_notes=data.get("top_notes"),
                mid_notes=data.get("mid_notes"),
                base_notes=data.get("base_notes"),
                concentration=data.get("concentration"),
                gender=data.get("gender"),
                year_released=data.get("year_released"),
                longevity_hours=data.get("longevity_hours"),
                projection=data.get("projection"),
                price_min=data.get("price_min"),
                price_max=data.get("price_max"),
                avg_rating=data.get("avg_rating", 0.0),
                review_count=data.get("review_count", 0)
            )
            db.add(fragrance)
        
        db.commit()
        print(f"Successfully seeded {len(FRAGRANCES_DATA)} fragrances!")
        
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    seed_fragrances()
